spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost:9099/~/kafkaAd
    username: sa
    password: a
    driver-class-name: org.h2.Driver
  quartz:
    auto-startup: true
    properties:
      org:
        quartz:
          jobstroe:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            misfireThreshold : 60000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
  kafka:
   bootstrap-servers: localhost:9092
   
   consumer:
      bootstrap-servers: localhost:9092
      group-id: JHB
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
mybatis:
  type-aliases-package: com.vtw.administrate
  mapper-locations: classpath*:mapper/**/*-mapper.xml